[package]
name = "rayquad"
version = "0.1.0"
authors = ["abstractqqq <qtren2015@gmail.com>"]
edition = "2021"
description = """
An opinionated, Raylib-like fork of Macroquad
"""
readme="README.md"
license = "MIT OR Apache-2.0"

[features]
audio = ["quad-snd"]
log-rs = ["log"]
glam-serde = ["glam/serde"]
default = []
rich-text = ["dep:parley"]

[package.metadata.android]
assets = "examples/"

[profile.dev.package."*"]
opt-level = 3

[package.metadata.docs.rs]
all-features = true

[dependencies]
miniquad = { version = "=0.4.11", features = ["log-impl"] }
quad-rand = "0.2.3"
glam = { version = "0.27", features = ["scalar-math"] }
image = { version = "0.24", default-features = false, features = ["png"] }
foldhash = "0.2"
parley = { version = "0.11", optional = true, default-features = false, features = ["std"] }
swash = "0.2"
backtrace = { version = "0.3.60", optional = true }
log = { version = "0.4", optional = true }
quad-snd = { version = "0.2", optional = true }

[[example]]
name = "rich_text_comparison"
path = "examples/rich_text_comparison.rs"
required-features = ["rich-text"]

[[example]]
name = "rich_text_comparison_chinese"
path = "examples/rich_text_comparison_chinese.rs"
required-features = ["rich-text"]

# workaround to fix the examples
# this allows companion crates in examples without two versions of rayquad
[patch.crates-io]
rayquad = { path = './' }
