[package]
name = "rayquad-tiled"
version = "0.1.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = """
Tiled editor integration for RayQuad
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoserde = "0.1"
foldhash = "0.2"
rayquad = { path = "../", version = "0.1.0" }
